[project]
name = "mix-contextvars-and-contextlib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "prettytable>=3.12.0",
    "slack-bolt>=1.22.0",
]
