[project]
name = "cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "core",
]

[tool.uv]
package = true

[tool.uv.sources]
core = { workspace = true }

[project.scripts]
radium226 = "radium226.cli:app"
