[project]
name = "data-platform"
version = "0.1.0"
requires-python = ">=3.13"


[tool.uv.workspace]
members = [
    "packages/core/spi",
    "packages/core/cli",
    "packages/tools/*",
    "packages/exports/*"    
]