[project]
name = "hello-message"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.uv]
package = true

[project.entry-points."radium226.messages"]
hello = "hello:provide_message"
